// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyBuffReducer from "../apply_buff_reducer";
import AttackReducer from "../attack_reducer";
import CompleteTutorialReducer from "../complete_tutorial_reducer";
import EndPhaseReducer from "../end_phase_reducer";
import EndTurnReducer from "../end_turn_reducer";
import ForfeitReducer from "../forfeit_reducer";
import JoinQueueReducer from "../join_queue_reducer";
import LeaveQueueReducer from "../leave_queue_reducer";
import PlayCardReducer from "../play_card_reducer";
import RegisterPlayerReducer from "../register_player_reducer";
import SetPlayerNameReducer from "../set_player_name_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UseHackReducer from "../use_hack_reducer";

export type ApplyBuffParams = __Infer<typeof ApplyBuffReducer>;
export type AttackParams = __Infer<typeof AttackReducer>;
export type CompleteTutorialParams = __Infer<typeof CompleteTutorialReducer>;
export type EndPhaseParams = __Infer<typeof EndPhaseReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type JoinQueueParams = __Infer<typeof JoinQueueReducer>;
export type LeaveQueueParams = __Infer<typeof LeaveQueueReducer>;
export type PlayCardParams = __Infer<typeof PlayCardReducer>;
export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type SetPlayerNameParams = __Infer<typeof SetPlayerNameReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UseHackParams = __Infer<typeof UseHackReducer>;

