// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  owner: __t.identity(),
  cardDefId: __t.u32().name("card_def_id"),
  location: __t.string(),
  fieldSlot: __t.u32().name("field_slot"),
  currentHp: __t.i32().name("current_hp"),
  currentAtk: __t.i32().name("current_atk"),
  canAttack: __t.bool().name("can_attack"),
  hasShield: __t.bool().name("has_shield"),
  hasDrain: __t.bool().name("has_drain"),
  stealthTurns: __t.u32().name("stealth_turns"),
  tempAtkBuff: __t.i32().name("temp_atk_buff"),
  deckOrder: __t.u32().name("deck_order"),
});
