// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  player1: __t.identity().name("player_1"),
  player2: __t.identity().name("player_2"),
  currentTurn: __t.identity().name("current_turn"),
  turnNumber: __t.u32().name("turn_number"),
  phase: __t.string(),
  p1Hp: __t.i32().name("p_1_hp"),
  p2Hp: __t.i32().name("p_2_hp"),
  p1Energy: __t.u32().name("p_1_energy"),
  p2Energy: __t.u32().name("p_2_energy"),
  p1MaxEnergy: __t.u32().name("p_1_max_energy"),
  p2MaxEnergy: __t.u32().name("p_2_max_energy"),
  status: __t.string(),
  winnerId: __t.string().name("winner_id"),
});
