// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  googleId: __t.string().name("google_id"),
  email: __t.string(),
  picture: __t.string(),
  isOnline: __t.bool().name("is_online"),
  isInQueue: __t.bool().name("is_in_queue"),
  wins: __t.u32(),
  losses: __t.u32(),
  tutorialCompleted: __t.bool().name("tutorial_completed"),
});
