// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CardInstance = __t.object("CardInstance", {
  id: __t.u64(),
  gameId: __t.u64(),
  owner: __t.identity(),
  cardDefId: __t.u32(),
  location: __t.string(),
  fieldSlot: __t.u32(),
  currentHp: __t.i32(),
  currentAtk: __t.i32(),
  canAttack: __t.bool(),
  hasShield: __t.bool(),
  hasDrain: __t.bool(),
  stealthTurns: __t.u32(),
  tempAtkBuff: __t.i32(),
  deckOrder: __t.u32(),
});
export type CardInstance = __Infer<typeof CardInstance>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  player1: __t.identity(),
  player2: __t.identity(),
  currentTurn: __t.identity(),
  turnNumber: __t.u32(),
  phase: __t.string(),
  p1Hp: __t.i32(),
  p2Hp: __t.i32(),
  p1Energy: __t.u32(),
  p2Energy: __t.u32(),
  p1MaxEnergy: __t.u32(),
  p2MaxEnergy: __t.u32(),
  status: __t.string(),
  winnerId: __t.string(),
});
export type Game = __Infer<typeof Game>;

export const GameLog = __t.object("GameLog", {
  id: __t.u64(),
  gameId: __t.u64(),
  turn: __t.u32(),
  eventType: __t.string(),
  message: __t.string(),
});
export type GameLog = __Infer<typeof GameLog>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  googleId: __t.string(),
  email: __t.string(),
  picture: __t.string(),
  isOnline: __t.bool(),
  isInQueue: __t.bool(),
  wins: __t.u32(),
  losses: __t.u32(),
  tutorialCompleted: __t.bool(),
});
export type Player = __Infer<typeof Player>;

