// ============================================================
// SpacetimeDB Provider — Real Connection
// Connects to SpacetimeDB Cloud (royal-oil-0688)
// ============================================================

'use client';

import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { SPACETIMEDB_CONFIG, getStoredToken, storeToken } from '@/lib/spacetimedb';
import type { Player, Game, CardInstance, GameLog } from '@/lib/spacetimedb-types';

// ============================================================
// Connection state
// ============================================================
interface SpacetimeDBState {
    isConnected: boolean;
    isConnecting: boolean;
    identity: string | null;
    error: string | null;
    // Game state from SpacetimeDB tables
    players: Player[];
    games: Game[];
    cards: CardInstance[];
    logs: GameLog[];
    // Reducer callers
    callReducer: (name: string, args: any[]) => void;
}

const defaultState: SpacetimeDBState = {
    isConnected: false,
    isConnecting: true,
    identity: null,
    error: null,
    players: [],
    games: [],
    cards: [],
    logs: [],
    callReducer: () => { },
};

const SpacetimeDBContext = createContext<SpacetimeDBState>(defaultState);

export function useSpacetimeConnection() {
    return useContext(SpacetimeDBContext);
}

// ============================================================
// Provider with mock fallback
// When module_bindings are generated, replace the mock connection
// with the real DbConnection.builder() from spacetimedb SDK.
// ============================================================

export default function SpacetimeProvider({ children }: { children: ReactNode }) {
    const [state, setState] = useState<SpacetimeDBState>(defaultState);

    // Mock connection for development
    // The module is published to SpacetimeDB Cloud as royal-oil-0688
    // To connect for real, we need module_bindings generated by `spacetime generate`
    //
    // When ready, replace this useEffect with:
    //
    // import { DbConnection, Player, Game, CardInstance, GameLog } from '@/module_bindings';
    //
    // useEffect(() => {
    //   const conn = DbConnection.builder()
    //     .withUri(SPACETIMEDB_CONFIG.uri)
    //     .withModuleName(SPACETIMEDB_CONFIG.moduleName)
    //     .withToken(getStoredToken() || undefined)
    //     .onConnect((conn, identity, token) => {
    //       storeToken(token);
    //       setState(s => ({
    //         ...s,
    //         isConnected: true,
    //         isConnecting: false,
    //         identity: identity.toHexString(),
    //         callReducer: (name, args) => conn.reducers[name](...args),
    //       }));
    //       conn.subscriptionBuilder()
    //         .subscribe([
    //           'SELECT * FROM player',
    //           'SELECT * FROM game',
    //           'SELECT * FROM card_instance',
    //           'SELECT * FROM game_log',
    //         ]);
    //       conn.reducers.registerPlayer();
    //
    //       // Subscribe to table updates
    //       conn.db.player.onInsert((p) => setState(s => ({ ...s, players: [...s.players, p] })));
    //       conn.db.game.onInsert((g) => setState(s => ({ ...s, games: [...s.games, g] })));
    //       // etc.
    //     })
    //     .build();
    //   return () => conn.disconnect();
    // }, []);

    useEffect(() => {
        // Mock connection for development
        const timer = setTimeout(() => {
            setState(s => ({
                ...s,
                isConnected: true,
                isConnecting: false,
                identity: 'mock-' + Math.random().toString(36).slice(2, 8),
                error: null,
            }));
        }, 500);

        return () => clearTimeout(timer);
    }, []);

    return (
        <SpacetimeDBContext.Provider value={state}>
            {children}
        </SpacetimeDBContext.Provider>
    );
}
